import type {Metadata} from 'next'

import {Inter} from 'next/font/google'
import {SideMenu} from "components/SideMenu";
import 'scss/_reset.scss'
import "primereact/resources/primereact.min.css";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import 'primeicons/primeicons.css';

const inter = Inter({subsets: ['latin']})


export const metadata: Metadata = {
    title: 'Карьер',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body style={{background: "#EFF3F8"}} className={inter.className}>
                <SideMenu/>
                {children}
            </body>
        </html>
    )
}
